site_name: DAGGERHEART SYSTEM REFERENCE
site_url: https://seansbox.github.io/daggerheart-srd/
repo_url: https://github.com/seansbox/daggerheart-srd
theme:
  name: material
  palette:
    scheme: slate
    primary: indigo
    accent: indigo
  favicon: favicon.png
  icon:
    logo: fontawesome/solid/fire-flame-curved
extra_css:
  - extra.css